name: "Kennedy's Garage"
permalink: pretty
author: Kennedy
email: kennedysgarage@gmail.com
url: http://kennedysgarage.com
title: Kennedy's Garage
description: Kennedy is a naively-optimistic entrepreneur living in New York City.
markdown: kramdown

include: ['_pages']

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

gems:
  - jekyll-assets
  - uglifier
  - sass

assets:
  dirname: assets
  baseurl: /assets/
  cache: false

sources:
  - _assets/fonts
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets

navigation:
- text: About
  url: /about/
- text: Projects
  url: /projects/
- text: Articles
  url: /articles/
- text: Hire
  url: mailto:kennedysgarage@gmail.com?subject=I Want To Hire You
