name: "Kennedy's Garage"
permalink: pretty

exclude: ["CNAME","editorconfig.txt","Gemfile","Gemfile.lock","README.md"]

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
